modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/KyoSohma/MoreOresArmorsAndTools/issues"

[[mods]]
    modId="moat"
    version="${file.jarVersion}"
    displayName="More Ores Armors and Tools"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/more-ores-armors-and-tools"
    logoFile="logo.png"
    credits="TurtyWurty and TechnoVision for the tutorials"
    authors="KyoSohma"
    description='''
Adds five new ores and seven new ingots/blocks, tool sets, and armor sets. Includes Tin, Copper, Bronze, Steel, Silver, Lead, and Platinum.
    '''

[[dependencies.moat]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
